Algoritmo "semnome"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 18/04/2023
Var
   contador : inteiro


Inicio
      Contador <- 100
      Repita
      Escreval (Contador)
      Contador <- Contador + 2
      Ate  Contador >= 200
      
Fimalgoritmo